/**
 * Video Generator
 * 
 * Creates detailed video storyboards for Reels, TikToks, and Stories.
 * Does NOT generate actual video - creates a storyboard that can be:
 * 1. Executed by a human videographer
 * 2. Assembled from stock footage + text overlays
 * 3. Generated by an AI video tool (Runway, Pika, etc.)
 */

export interface VideoScene {
  sceneNumber: number;
  startTime: number;
  endTime: number;
  duration: number;
  visual: string;
  camera: string;
  textOverlay?: {
    text: string;
    position: "center" | "bottom_third" | "top" | "bottom";
    animation: "fade_in" | "type_on" | "slide_up" | "pop" | "none";
    font: string;
    color: string;
    size: string;
    background?: string;
  };
  voiceover?: string;
  onScreenAction?: string;
  bRoll?: string;
  transition: string;
}

export interface VideoAudio {
  type: "trending_sound" | "original_voiceover" | "background_music" | "mixed";
  trendingSoundSuggestion?: string;
  musicMood?: string;
  voiceoverScript?: string;
}

export interface VideoHook {
  firstFrame: string;
  hookStrategy: "question" | "transformation" | "shock" | "curiosity_gap" | "statement" | "result";
}

export interface VideoCover {
  imagePrompt: string;
  hookText: string;
}

export interface VideoStoryboard {
  id: string;
  platform: string;
  contentType: "REEL" | "STORY" | "TikTok";
  aspectRatio: "9:16" | "16:9" | "1:1";
  duration: number;
  scenes: VideoScene[];
  audio: VideoAudio;
  hook: VideoHook;
  coverImage: VideoCover;
  cta: string;
  captions: string[];
}

export interface GenerateVideoOptions {
  platform: string;
  contentType: "REEL" | "STORY" | "TikTok";
  caption: string;
  tone?: string;
  duration?: number; // Target duration in seconds
  includeVoiceover?: boolean;
  useTrendingAudio?: boolean;
}

/**
 * Generate a video storyboard from caption
 */
export function generateVideoStoryboard(
  options: GenerateVideoOptions
): VideoStoryboard {
  const {
    platform,
    contentType,
    caption,
    tone = "professional",
    duration: targetDuration = 30,
    includeVoiceover = false,
    useTrendingAudio = true,
  } = options;

  const id = `video-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  const aspectRatio: "9:16" = "9:16";

  // Parse caption for key content
  const isEducational = /\d+\s+(tips|ways|steps|things|reasons)/.test(caption);
  const isProductFeature = /feature|introducing|new|launch|product/i.test(caption);
  const isTestimonial = /customer|client|review|testimonial/i.test(caption);
  const isHowTo = /how to|learn|tutorial/i.test(caption);

  // Generate scenes based on content type
  const scenes = generateScenes(caption, targetDuration, {
    isEducational,
    isProductFeature,
    isTestimonial,
    isHowTo,
    tone,
  });

  // Calculate actual duration
  const actualDuration = scenes.reduce((sum, s) => sum + s.duration, 0);

  // Generate audio config
  const audio: VideoAudio = {
    type: useTrendingAudio ? "trending_sound" : includeVoiceover ? "original_voiceover" : "background_music",
    trendingSoundSuggestion: useTrendingAudio ? getTrendingSound(platform, tone) : undefined,
    musicMood: tone,
    voiceoverScript: includeVoiceover ? caption : undefined,
  };

  // Generate hook
  const hook = generateHook(caption, scenes[0]?.visual || "");

  // Generate cover image
  const coverImage: VideoCover = {
    imagePrompt: `${scenes[0]?.visual || caption.substring(0, 50)}, ${tone} style, vertical video thumbnail, eye-catching`,
    hookText: caption.substring(0, 30),
  };

  // Generate CTA
  const cta = generateCTA(platform);

  // Generate captions for auto-captioning
  const captions = scenes
    .filter(s => s.textOverlay?.text)
    .map(s => s.textOverlay!.text);

  return {
    id,
    platform,
    contentType,
    aspectRatio,
    duration: actualDuration,
    scenes,
    audio,
    hook,
    coverImage,
    cta,
    captions,
  };
}

/**
 * Generate scenes based on content type
 */
function generateScenes(
  caption: string,
  targetDuration: number,
  context: {
    isEducational: boolean;
    isProductFeature: boolean;
    isTestimonial: boolean;
    isHowTo: boolean;
    tone: string;
  }
): VideoScene[] {
  const scenes: VideoScene[] = [];
  
  // Hook scene (0-3 seconds)
  scenes.push({
    sceneNumber: 1,
    startTime: 0,
    endTime: 3,
    duration: 3,
    visual: `Attention-grabbing ${context.tone} moment related to: ${caption.substring(0, 50)}`,
    camera: "static",
    textOverlay: {
      text: caption.substring(0, 30),
      position: "center",
      animation: "pop",
      font: "bold",
      color: "white",
      size: "large",
      background: "rgba(0,0,0,0.5)",
    },
    transition: "cut",
  });

  if (context.isEducational || context.isHowTo) {
    // Educational content - multiple short scenes
    const points = extractKeyPoints(caption);
    const pointDuration = Math.min(5, (targetDuration - 5) / points.length);
    
    let currentTime = 3;
    points.slice(0, 4).forEach((point, i) => {
      scenes.push({
        sceneNumber: i + 2,
        startTime: currentTime,
        endTime: currentTime + pointDuration,
        duration: pointDuration,
        visual: `Demonstration of: ${point}`,
        camera: i % 2 === 0 ? "overhead" : "medium",
        textOverlay: {
          text: point,
          position: "bottom_third",
          animation: "slide_up",
          font: "regular",
          color: "white",
          size: "medium",
        },
        transition: "cut",
      });
      currentTime += pointDuration;
    });
  } else if (context.isProductFeature) {
    // Product feature - show product, then benefits
    scenes.push({
      sceneNumber: 2,
      startTime: 3,
      endTime: 10,
      duration: 7,
      visual: "Product close-up, high quality, well-lit",
      camera: "slow_zoom_in",
      textOverlay: {
        text: "Introducing our latest",
        position: "top",
        animation: "fade_in",
        font: "bold",
        color: "white",
        size: "medium",
      },
      transition: "fade",
    });

    scenes.push({
      sceneNumber: 3,
      startTime: 10,
      endTime: targetDuration,
      duration: targetDuration - 10,
      visual: "Product in use, lifestyle context",
      camera: "medium",
      textOverlay: {
        text: extractBenefit(caption),
        position: "bottom_third",
        animation: "slide_up",
        font: "regular",
        color: "white",
        size: "medium",
      },
      transition: "cut",
    });
  } else if (context.isTestimonial) {
    // Testimonial - customer story
    scenes.push({
      sceneNumber: 2,
      startTime: 3,
      endTime: 15,
      duration: 12,
      visual: "Customer sharing experience, authentic setting",
      camera: "medium",
      voiceover: caption,
      transition: "fade",
    });
  } else {
    // Default - narrative flow
    scenes.push({
      sceneNumber: 2,
      startTime: 3,
      endTime: targetDuration - 5,
      duration: targetDuration - 8,
      visual: `Main content: ${caption.substring(0, 100)}`,
      camera: "medium",
      transition: "cut",
    });
  }

  // CTA scene
  scenes.push({
    sceneNumber: scenes.length + 1,
    startTime: targetDuration - 5,
    endTime: targetDuration,
    duration: 5,
    visual: "End screen with CTA",
    camera: "static",
    textOverlay: {
      text: "Follow for more!",
      position: "center",
      animation: "pop",
      font: "bold",
      color: "white",
      size: "large",
    },
    transition: "fade",
  });

  return scenes;
}

/**
 * Extract key points from educational content
 */
function extractKeyPoints(caption: string): string[] {
  const matches = caption.match(/\d+\.\s*[^.]+/g);
  if (matches) {
    return matches.map(m => m.replace(/^\d+\.\s*/, "").trim());
  }
  
  // Fallback: split by sentences
  return caption
    .split(/[.!?]/)
    .filter(s => s.trim().length > 10)
    .slice(0, 5)
    .map(s => s.trim());
}

/**
 * Extract benefit from caption
 */
function extractBenefit(caption: string): string {
  const benefitMatch = caption.match(/helps? (.*?)[\.]/i);
  return benefitMatch ? benefitMatch[1] : "Amazing results";
}

/**
 * Generate hook based on content
 */
function generateHook(caption: string, firstVisual: string): VideoHook {
  const isQuestion = caption.startsWith("?") || caption.startsWith("How");
  const isStatement = /^\d+/.test(caption);
  
  let hookStrategy: VideoHook["hookStrategy"] = "statement";
  
  if (isQuestion) {
    hookStrategy = "question";
  } else if (/secret|reveal|truth|shocking/i.test(caption)) {
    hookStrategy = "shock";
  } else if (/before|after|transformation/i.test(caption)) {
    hookStrategy = "transformation";
  } else if (/won't believe|wait till|see what/i.test(caption)) {
    hookStrategy = "curiosity_gap";
  }

  return {
    firstFrame: firstVisual || caption.substring(0, 50),
    hookStrategy,
  };
}

/**
 * Generate CTA based on platform
 */
function generateCTA(platform: string): string {
  const ctas: Record<string, string> = {
    instagram: "Follow for more tips! 💫",
    tiktok: "Follow for more! 🎵",
    linkedin: "Follow for professional insights",
    facebook: "Like and follow for more",
    default: "Follow for more!",
  };
  
  return ctas[platform.toLowerCase()] || ctas.default;
}

/**
 * Get trending sound suggestion based on platform and tone
 */
function getTrendingSound(platform: string, tone: string): string {
  // These would be dynamically fetched from an API in production
  const sounds: Record<string, Record<string, string>> = {
    instagram: {
      energetic: "Trending upbeat #viral #trending",
      calm: "Chill lo-fi beats #study #relax",
      professional: "Corporate ambient #business",
    },
    tiktok: {
      energetic: "Viral sound 2024 #fyp #viral",
      funny: "Comedy sound effect #funny #lol",
      educational: "Trending #learn #tips",
    },
    linkedin: {
      professional: "Professional background #business",
      motivational: "Inspiring #success #motivation",
    },
  };

  return sounds[platform.toLowerCase()]?.[tone] || sounds[platform.toLowerCase()]?.energetic || "Trending audio";
}

/**
 * Export storyboard to JSON for human videographer
 */
export function exportStoryboardJSON(storyboard: VideoStoryboard): string {
  return JSON.stringify(storyboard, null, 2);
}

/**
 * Estimate video production cost (for internal tracking)
 */
export function estimateVideoCost(storyboard: VideoStoryboard): {
  aiGeneration: number;
  humanEditing: number;
  stockFootage: number;
  total: number;
} {
  // Rough estimates
  const sceneCount = storyboard.scenes.length;
  const aiGeneration = sceneCount * 0.50; // AI video generation (Runway, etc.)
  const humanEditing = sceneCount * 5; // Human editor time
  const stockFootage = sceneCount * 2; // Stock footage licensing

  return {
    aiGeneration,
    humanEditing,
    stockFootage,
    total: aiGeneration + humanEditing + stockFootage,
  };
}
